#Introduction to NumPy 

![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png)

NumPy (or Numpy) is a Linear Algebra Library for Python. NumPy is a Python package. It stands for 'Numerical Python'. It is a library consisting of multidimensional array objects and a collection of routines for processing of array.

Numpy is also incredibly fast, as it has bindings to C libraries.

## **About iPython Notebooks**

iPython Notebooks are interactive coding environments embedded in a webpage. You will be using iPython notebooks in this class. You only need to write code between the ### START CODE HERE ### and ### END CODE HERE ### comments. After writing your code, you can run the cell by either pressing "SHIFT"+"ENTER" or by clicking on "Run Cell" (denoted by a play symbol) in the left bar of the cell.


**In this notebook you will learn -**
* Numpy arrays
* Numpy Selecting and Indexing
* Numpy Operations

## Importing NumPy

To import NumPy in Colaboratory under the name **np** type the following:


In [0]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors, arrays, matrices, and number generation. Let's start with arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d.

**Note:** A matrix can still have only one row or one column.


## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [0]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [0]:
np.array(my_list)

array([1, 2, 3])

In [0]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]      # list of lists
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [0]:
np.array(my_matrix)      # 3x3 matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Exercise 1.1:**

Create a list named **odd_list** containing all odd numbers from 0 to 10 and print it.

In [1]:
### START CODE HERE ### (2 lines of code)
odd_list = [1,3,5,7,9]
odd_list
### END CODE HERE ###

[1, 3, 5, 7, 9]

**Expected Output:**

[1, 3, 5, 7, 9]

**Exercise 1.2:**

Create a 2x2 matrix of all even numbers from 1 to 9.

In [4]:
### START CODE HERE ###
import numpy as np
matrix = [[2,4],[6,8]]                      #create list of 2 lists
matrix                                      #print the list
np.array(matrix)                            #convert the list into array
  
### END CODE HERE ###

array([[2, 4],
       [6, 8]])

**Expected Output:**

array[[2, 4],

     [6,8]]

#Built-in Methods

There are lots of built-in ways to generate Arrays.

### arange

Return evenly spaced values within a given interval.

In [0]:
np.arange(0,10)     #creates an array from 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Note:** 
The first parameter is the starting value and second parameter (excluding) is the ending value.

In [0]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

**Note:** 
The third parameter is the step value.

**Exercise 1.3:**

Create an array of odd numbers between 30 to 40 using **arange** function.

In [5]:
### START CODE HERE ###
import numpy as np
np.arange(31,40,2)
### END CODE HERE ###

array([31, 33, 35, 37, 39])

**Expected Output:**

[31, 33, 35, 37, 39]

### zeros and ones

Generate arrays of zeros or ones

In [0]:
np.zeros(3)      #creates an array of 3 zeros

array([0., 0., 0.])

In [0]:
np.zeros((5,5))      #creates a 5x5 matrix of zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [0]:
np.ones(3)      #creates an array of 3 ones

array([1., 1., 1.])

In [0]:
np.ones((3,3))      #creates a 5x5 matrix of ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Linspace

 Returns number spaces evenly w.r.t interval. Similiar to arange but instead of step it uses sample number.

numpy.linspace(start, stop, num = 50, endpoint = True, retstep = False, dtype = None,axis = 0)
 
 Parameters :

* start  : [optional] start of interval range. By default start = 0

* stop   : end of interval range, unless endpoint is set to False.In that case, the sequence consists of all but the last.

* num    : [int, optional] No. of samples to generate.Default is 50. Must be non-negative.

* endpoint   :  [bool, optional] If True, stop is the last sample. Otherwise, it is not included. Default is True.

* restep :  [bool, optional] If True, return (samples, step,)where step is the spacing between samples. By deflut restep = False.

* dtype  : [dtype, optional] The type of the output array. If dtype is not given, infer the data type from the other input arguments.

*axis  :  [int, optional] The axis in the result to store the samples. Relevant only if start or stop are array-like. By default (0), the samples will be along a new axis inserted at the beginning. Use -1 to get an axis at the end.

In [0]:
np.linspace(0,10,5)                 #5 intervals generated between 0 and 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [0]:
np.linspace(0,10,50)                #50 intervals generated between 0 and 10

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### eye

Creates an identity matrix

In [0]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

###Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1]``.

In [0]:
np.random.rand(2)

array([0.09424201, 0.9729102 ])

In [0]:
np.random.rand(5,5)

array([[0.96119769, 0.66654362, 0.44037671, 0.99077464, 0.67054731],
       [0.7632278 , 0.76418321, 0.50759305, 0.23413845, 0.97802182],
       [0.7880287 , 0.96950813, 0.06866801, 0.80372106, 0.41532078],
       [0.76720641, 0.79674922, 0.89244394, 0.59624529, 0.53143292],
       [0.16466125, 0.03960232, 0.47130774, 0.82437061, 0.93424583]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [0]:
np.random.randn(2)

array([-0.35950875,  0.55235977])

In [0]:
np.random.randn(5,5)

array([[ 0.70154515,  0.22441999,  1.33563186,  0.82872577, -0.28247509],
       [ 0.64489788,  0.61815094, -0.81693168, -0.30102424, -0.29030574],
       [ 0.8695976 ,  0.413755  ,  2.20047208,  0.17955692, -0.82159344],
       [ 0.59264235,  1.29869894, -1.18870241,  0.11590888, -0.09181687],
       [-0.96924265, -1.62888685, -2.05787102, -0.29705576,  0.68915542]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [0]:
np.random.randint(1,100)

44

In [0]:
np.random.randint(1,100,10)      #print 10 values between 1 to 100

array([13, 64, 27, 63, 46, 68, 92, 10, 58, 24])

**Note:**
The third parameter indicates the number of values to be printed.

# Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [0]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [0]:
ranarr

array([35, 40, 41, 18,  8, 42, 42, 24, 38, 15])

### Reshape
Returns an array containing the same data with a new shape.

In [0]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [0]:
ranarr

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [0]:
ranarr.max()      #prints the maximum value in the array

49

In [0]:
ranarr.argmax()      #prints the index of the max value

4

In [0]:
ranarr.min()      #prints the minimum value in the array

2

In [0]:
ranarr.argmin()      #prints the index of the max value

5

### Shape

Shape is an attribute that arrays have (not a method). It gives you the shape if the array(M x N).

In [0]:
# Vector
arr.shape

(25,)

In [0]:
# Notice the two sets of brackets
arr.reshape(1,25)

In [0]:
arr.reshape(1,25).shape

(1, 25)

In [0]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [0]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [0]:
arr.dtype

dtype('int64')

**Exercise 1.4:**

Create a random array of 15 numbers from 10 to 40. Reshape the same array to 3x5 matrix. Also print the min and max numbers from that array list.

In [9]:
### START CODE HERE ###  
import numpy as np
arr = np.random.randint(10,40,15)      #create random array
arr                                    #print the array
arr.reshape(3,5)                       #reshape the array

array([[24, 17, 36, 33, 25],
       [16, 26, 29, 19, 14],
       [22, 16, 38, 24, 38]])

In [10]:
a = arr.min()                          #get the minimum value
a

14

In [11]:
b = arr.max()                          #get the maximum value
b
### END CODE HERE ###


38

# Great Job!